package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.BookRecommendDO;

public interface BookRecommendDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_recommend
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    int deleteByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_recommend
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    int insert(BookRecommendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_recommend
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    int insertSelective(BookRecommendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_recommend
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    BookRecommendDO selectByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_recommend
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    int updateByPrimaryKeySelective(BookRecommendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books_recommend
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    int updateByPrimaryKey(BookRecommendDO record);
}