package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.BrowsingRecordDO;

public interface BrowsingRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_records
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int deleteByPrimaryKey(Long browsingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_records
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int insert(BrowsingRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_records
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int insertSelective(BrowsingRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_records
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    BrowsingRecordDO selectByPrimaryKey(Long browsingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_records
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int updateByPrimaryKeySelective(BrowsingRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_records
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int updateByPrimaryKey(BrowsingRecordDO record);
}