package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.PurchaseHistoryDO;

public interface PurchaseHistoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated Thu May 21 16:27:45 CST 2020
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated Thu May 21 16:27:45 CST 2020
     */
    int insert(PurchaseHistoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated Thu May 21 16:27:45 CST 2020
     */
    int insertSelective(PurchaseHistoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated Thu May 21 16:27:45 CST 2020
     */
    PurchaseHistoryDO selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated Thu May 21 16:27:45 CST 2020
     */
    int updateByPrimaryKeySelective(PurchaseHistoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_history
     *
     * @mbg.generated Thu May 21 16:27:45 CST 2020
     */
    int updateByPrimaryKey(PurchaseHistoryDO record);
}