package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.ReviewAgreeLogDOKey;

public interface ReviewAgreeLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:21:11 CST 2020
     */
    int deleteByPrimaryKey(ReviewAgreeLogDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:21:11 CST 2020
     */
    int insert(ReviewAgreeLogDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:21:11 CST 2020
     */
    int insertSelective(ReviewAgreeLogDOKey record);
}