package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.ReviewAgreeLogDO;
import com.example.springwebserver.dataObject.ReviewAgreeLogDOKey;

public interface ReviewAgreeLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    int deleteByPrimaryKey(ReviewAgreeLogDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    int insert(ReviewAgreeLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    int insertSelective(ReviewAgreeLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    ReviewAgreeLogDO selectByPrimaryKey(ReviewAgreeLogDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    int updateByPrimaryKeySelective(ReviewAgreeLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_agree_log
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    int updateByPrimaryKey(ReviewAgreeLogDO record);
}