package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.BookDO;
import com.example.springwebserver.dataObject.TagDO;
import com.github.pagehelper.Page;

import java.util.List;

public interface TagDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int insert(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int insertSelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    TagDO selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int updateByPrimaryKeySelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    int updateByPrimaryKey(TagDO record);

    List<TagDO> listTagByTagIDs(List<String> tags);
}