package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Wed May 20 16:57:13 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Wed May 20 16:57:13 CST 2020
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Wed May 20 16:57:13 CST 2020
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Wed May 20 16:57:13 CST 2020
     */
    UserPasswordDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Wed May 20 16:57:13 CST 2020
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_password
     *
     * @mbg.generated Wed May 20 16:57:13 CST 2020
     */
    int updateByPrimaryKey(UserPasswordDO record);
}