package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.UserHasReadDO;

public interface UserHasReadDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_has_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_has_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int insert(UserHasReadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_has_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int insertSelective(UserHasReadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_has_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    UserHasReadDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_has_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int updateByPrimaryKeySelective(UserHasReadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_has_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int updateByPrimaryKey(UserHasReadDO record);
}