package com.example.springwebserver.dao;

import com.example.springwebserver.dataObject.UserWantReadDO;

public interface UserWantReadDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_want_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_want_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int insert(UserWantReadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_want_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int insertSelective(UserWantReadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_want_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    UserWantReadDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_want_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int updateByPrimaryKeySelective(UserWantReadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_want_read
     *
     * @mbg.generated Sun May 24 23:54:15 CST 2020
     */
    int updateByPrimaryKey(UserWantReadDO record);
}