spring:
  profiles:
    active: dev
  datasource:
    name: bookRecommend
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: book_recommend
    url: jdbc:mysql://bookrecommend.rwlb.rds.aliyuncs.com:3306/book_recommend?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    default-property-inclusion: non_null

  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 50
        min-idle: 20
    timeout: 5000


server:
  port: 8090
  tomcat:
    accept-count: 1000
    threads:
      min-spare: 100
      max: 800

mybatis:
  mapper-locations: classpath:mapping/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.example.springwebserver.dao: debug


