package com.example.springwebserver.dataObject;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.user_id
     *
     * @mbg.generated Mon Jun 08 11:04:35 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.level
     *
     * @mbg.generated Mon Jun 08 11:04:35 CST 2020
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.user_id
     *
     * @return the value of admins.user_id
     *
     * @mbg.generated Mon Jun 08 11:04:35 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.user_id
     *
     * @param userId the value for admins.user_id
     *
     * @mbg.generated Mon Jun 08 11:04:35 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.level
     *
     * @return the value of admins.level
     *
     * @mbg.generated Mon Jun 08 11:04:35 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.level
     *
     * @param level the value for admins.level
     *
     * @mbg.generated Mon Jun 08 11:04:35 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}