package com.example.springwebserver.dataObject;

public class AuthorDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.author_id
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    private Long authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.author_name
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.country_id
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    private Integer countryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.author_id
     *
     * @return the value of authors.author_id
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.author_id
     *
     * @param authorId the value for authors.author_id
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.author_name
     *
     * @return the value of authors.author_name
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.author_name
     *
     * @param authorName the value for authors.author_name
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.country_id
     *
     * @return the value of authors.country_id
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.country_id
     *
     * @param countryId the value for authors.country_id
     *
     * @mbg.generated Thu May 21 14:48:38 CST 2020
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }
}