package com.example.springwebserver.dataObject;

public class BookRecommendDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_recommend.book_id
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books_recommend.books
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    private String books;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_recommend.book_id
     *
     * @return the value of books_recommend.book_id
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_recommend.book_id
     *
     * @param bookId the value for books_recommend.book_id
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books_recommend.books
     *
     * @return the value of books_recommend.books
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    public String getBooks() {
        return books;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books_recommend.books
     *
     * @param books the value for books_recommend.books
     *
     * @mbg.generated Sun May 24 19:00:26 CST 2020
     */
    public void setBooks(String books) {
        this.books = books == null ? null : books.trim();
    }
}