package com.example.springwebserver.dataObject;

public class RatingDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.user_id
     *
     * @mbg.generated Fri May 22 18:05:45 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.book_id
     *
     * @mbg.generated Fri May 22 18:05:45 CST 2020
     */
    private Long bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.user_id
     *
     * @return the value of ratings.user_id
     *
     * @mbg.generated Fri May 22 18:05:45 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.user_id
     *
     * @param userId the value for ratings.user_id
     *
     * @mbg.generated Fri May 22 18:05:45 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.book_id
     *
     * @return the value of ratings.book_id
     *
     * @mbg.generated Fri May 22 18:05:45 CST 2020
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.book_id
     *
     * @param bookId the value for ratings.book_id
     *
     * @mbg.generated Fri May 22 18:05:45 CST 2020
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }
}