package com.example.springwebserver.dataObject;

import java.util.Date;

public class RatingDO extends RatingDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.rating
     *
     * @mbg.generated Wed May 27 21:58:22 CST 2020
     */
    private Double rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.time
     *
     * @mbg.generated Wed May 27 21:58:22 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.rating
     *
     * @return the value of ratings.rating
     *
     * @mbg.generated Wed May 27 21:58:22 CST 2020
     */
    public Double getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.rating
     *
     * @param rating the value for ratings.rating
     *
     * @mbg.generated Wed May 27 21:58:22 CST 2020
     */
    public void setRating(Double rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.time
     *
     * @return the value of ratings.time
     *
     * @mbg.generated Wed May 27 21:58:22 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.time
     *
     * @param time the value for ratings.time
     *
     * @mbg.generated Wed May 27 21:58:22 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}