package com.example.springwebserver.dataObject;

import java.util.Date;

public class ReviewAgreeLogDO extends ReviewAgreeLogDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_agree_log.time
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_agree_log.time
     *
     * @return the value of reviews_agree_log.time
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_agree_log.time
     *
     * @param time the value for reviews_agree_log.time
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}