package com.example.springwebserver.dataObject;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class ReviewDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.review_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Long reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.book_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.user_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.content
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.star
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Integer star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.buy_time
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Date buyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.agree_number
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Integer agreeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews.review_time
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    private Date reviewTime;

    private String coverUrl;

    private String bookName;

    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.review_id
     *
     * @return the value of reviews.review_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Long getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.review_id
     *
     * @param reviewId the value for reviews.review_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.book_id
     *
     * @return the value of reviews.book_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.book_id
     *
     * @param bookId the value for reviews.book_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.user_id
     *
     * @return the value of reviews.user_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.user_id
     *
     * @param userId the value for reviews.user_id
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.content
     *
     * @return the value of reviews.content
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.content
     *
     * @param content the value for reviews.content
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.star
     *
     * @return the value of reviews.star
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.star
     *
     * @param star the value for reviews.star
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.buy_time
     *
     * @return the value of reviews.buy_time
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.buy_time
     *
     * @param buyTime the value for reviews.buy_time
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.agree_number
     *
     * @return the value of reviews.agree_number
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Integer getAgreeNumber() {
        return agreeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.agree_number
     *
     * @param agreeNumber the value for reviews.agree_number
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setAgreeNumber(Integer agreeNumber) {
        this.agreeNumber = agreeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews.review_time
     *
     * @return the value of reviews.review_time
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews.review_time
     *
     * @param reviewTime the value for reviews.review_time
     *
     * @mbg.generated Thu May 21 21:11:28 CST 2020
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }
}