package com.example.springwebserver.dataObject;

public class ReviewAgreeLogDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_agree_log.review_id
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    private Long reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_agree_log.user_id
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_agree_log.review_id
     *
     * @return the value of reviews_agree_log.review_id
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    public Long getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_agree_log.review_id
     *
     * @param reviewId the value for reviews_agree_log.review_id
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_agree_log.user_id
     *
     * @return the value of reviews_agree_log.user_id
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_agree_log.user_id
     *
     * @param userId the value for reviews_agree_log.user_id
     *
     * @mbg.generated Thu May 28 14:29:44 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}