package com.example.springwebserver.dataObject;

public class UserRecommendDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_recommend.user_id
     *
     * @mbg.generated Sun May 24 20:14:54 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_recommend.books
     *
     * @mbg.generated Sun May 24 20:14:54 CST 2020
     */
    private String books;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_recommend.user_id
     *
     * @return the value of users_recommend.user_id
     *
     * @mbg.generated Sun May 24 20:14:54 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_recommend.user_id
     *
     * @param userId the value for users_recommend.user_id
     *
     * @mbg.generated Sun May 24 20:14:54 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_recommend.books
     *
     * @return the value of users_recommend.books
     *
     * @mbg.generated Sun May 24 20:14:54 CST 2020
     */
    public String getBooks() {
        return books;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_recommend.books
     *
     * @param books the value for users_recommend.books
     *
     * @mbg.generated Sun May 24 20:14:54 CST 2020
     */
    public void setBooks(String books) {
        this.books = books == null ? null : books.trim();
    }
}